# Generated by Django 4.0.4 on 2022-05-26 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_item_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='nome',
            new_name='title',
        ),
    ]
